<!DOCTYPE html><html lang="en" mode="dark" ><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"><meta name="day-prompt" content="days ago"><meta name="hour-prompt" content="hours ago"><meta name="minute-prompt" content="minutes ago"><meta name="justnow-prompt" content="just now"><meta name="generator" content="Jekyll v4.2.1" /><meta property="og:title" content="async/await_3 Excention 2" /><meta property="og:locale" content="en" /><meta name="description" content="about exception of void return. 쉽게, sync에서 먼저. 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 class asaw_4_sync { public void ThrowException() { throw new InvalidOperationException(); } public void SyncExceptions() { try { ThrowException(); } catch (Exception) { // The exception is never caught here! throw; } } } //////////////////////////////////////////////////// private void button1_Click(object sender, EventArgs e) { try { aa4s.SyncExceptions(); } catch (Exception ex) { textBox1.AppendText(ex.Message + Environment.NewLine); } } 예상 가능한 결과로 호출은 button event =&gt; SyncExceptions() =&gt; ThrowException() 으로, Exceptions은 ThrowException() =&gt; SyncExceptions() =&gt; button event로 잘 타고 온다. 항상 보던 당연한 결말. 위 방식을 async로 바꿔해본다. 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 class ASAW_4_async_1 { public async void ThrowException() { throw new InvalidOperationException(); } public void AsyncExceptions() { try { ThrowException(); } catch (Exception) { // The exception is never caught here! throw; } } } ////////////////// private void button2_Click(object sender, EventArgs e) { try { aa4a_1.AsyncExceptions(); } catch (Exception ex) { textBox1.AppendText(ex.Message + Environment.NewLine); } } 바뀐점은 ThrowException()가 async로 된것, 또 하지말라던 void로 한것. 호출은 button event =&gt; AsyncExceptions() =&gt; ThrowException()으로 동일, Exception은 throw new InvalidOperationException(); 에서 멈춘다. 저 라인에서 throw를 못한다." /><meta property="og:description" content="about exception of void return. 쉽게, sync에서 먼저. 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 class asaw_4_sync { public void ThrowException() { throw new InvalidOperationException(); } public void SyncExceptions() { try { ThrowException(); } catch (Exception) { // The exception is never caught here! throw; } } } //////////////////////////////////////////////////// private void button1_Click(object sender, EventArgs e) { try { aa4s.SyncExceptions(); } catch (Exception ex) { textBox1.AppendText(ex.Message + Environment.NewLine); } } 예상 가능한 결과로 호출은 button event =&gt; SyncExceptions() =&gt; ThrowException() 으로, Exceptions은 ThrowException() =&gt; SyncExceptions() =&gt; button event로 잘 타고 온다. 항상 보던 당연한 결말. 위 방식을 async로 바꿔해본다. 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 class ASAW_4_async_1 { public async void ThrowException() { throw new InvalidOperationException(); } public void AsyncExceptions() { try { ThrowException(); } catch (Exception) { // The exception is never caught here! throw; } } } ////////////////// private void button2_Click(object sender, EventArgs e) { try { aa4a_1.AsyncExceptions(); } catch (Exception ex) { textBox1.AppendText(ex.Message + Environment.NewLine); } } 바뀐점은 ThrowException()가 async로 된것, 또 하지말라던 void로 한것. 호출은 button event =&gt; AsyncExceptions() =&gt; ThrowException()으로 동일, Exception은 throw new InvalidOperationException(); 에서 멈춘다. 저 라인에서 throw를 못한다." /><link rel="canonical" href="https://psy0231.github.io/posts/CS_12_Async&Await_4/" /><meta property="og:url" content="https://psy0231.github.io/posts/CS_12_Async&Await_4/" /><meta property="og:site_name" content="Null Section" /><meta property="og:type" content="article" /><meta property="article:published_time" content="2021-03-31T12:00:00+09:00" /><meta name="twitter:card" content="summary" /><meta property="twitter:title" content="async/await_3 Excention 2" /><meta name="twitter:site" content="@twitter_username" /><meta name="google-site-verification" content="google_meta_tag_verification" /> <script type="application/ld+json"> {"description":"about exception of void return. 쉽게, sync에서 먼저. 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 class asaw_4_sync { public void ThrowException() { throw new InvalidOperationException(); } public void SyncExceptions() { try { ThrowException(); } catch (Exception) { // The exception is never caught here! throw; } } } //////////////////////////////////////////////////// private void button1_Click(object sender, EventArgs e) { try { aa4s.SyncExceptions(); } catch (Exception ex) { textBox1.AppendText(ex.Message + Environment.NewLine); } } 예상 가능한 결과로 호출은 button event =&gt; SyncExceptions() =&gt; ThrowException() 으로, Exceptions은 ThrowException() =&gt; SyncExceptions() =&gt; button event로 잘 타고 온다. 항상 보던 당연한 결말. 위 방식을 async로 바꿔해본다. 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 class ASAW_4_async_1 { public async void ThrowException() { throw new InvalidOperationException(); } public void AsyncExceptions() { try { ThrowException(); } catch (Exception) { // The exception is never caught here! throw; } } } ////////////////// private void button2_Click(object sender, EventArgs e) { try { aa4a_1.AsyncExceptions(); } catch (Exception ex) { textBox1.AppendText(ex.Message + Environment.NewLine); } } 바뀐점은 ThrowException()가 async로 된것, 또 하지말라던 void로 한것. 호출은 button event =&gt; AsyncExceptions() =&gt; ThrowException()으로 동일, Exception은 throw new InvalidOperationException(); 에서 멈춘다. 저 라인에서 throw를 못한다.","headline":"async/await_3 Excention 2","dateModified":"2021-07-03T12:49:33+09:00","datePublished":"2021-03-31T12:00:00+09:00","url":"https://psy0231.github.io/posts/CS_12_Async&Await_4/","@type":"BlogPosting","mainEntityOfPage":{"@type":"WebPage","@id":"https://psy0231.github.io/posts/CS_12_Async&Await_4/"},"@context":"https://schema.org"}</script><title>12. async/await_3 Excention 2 | Null Section</title><link rel="apple-touch-icon" sizes="180x180" href="/assets/img/favicons/apple-touch-icon.png"><link rel="icon" type="image/png" sizes="32x32" href="/assets/img/favicons/favicon-32x32.png"><link rel="icon" type="image/png" sizes="16x16" href="/assets/img/favicons/favicon-16x16.png"><link rel="manifest" href="/assets/img/favicons/site.webmanifest"><link rel="shortcut icon" href="/assets/img/favicons/favicon.ico"><meta name="apple-mobile-web-app-title" content="Null Section"><meta name="application-name" content="Null Section"><meta name="msapplication-TileColor" content="#da532c"><meta name="msapplication-config" content="/assets/img/favicons/browserconfig.xml"><meta name="theme-color" content="#ffffff"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="anonymous"><link rel="dns-prefetch" href="https://fonts.gstatic.com"><link rel="preconnect" href="https://www.google-analytics.com" crossorigin="use-credentials"><link rel="dns-prefetch" href="https://www.google-analytics.com"><link rel="preconnect" href="https://www.googletagmanager.com" crossorigin="anonymous"><link rel="dns-prefetch" href="https://www.googletagmanager.com"><link rel="preconnect" href="https://cdn.jsdelivr.net"><link rel="dns-prefetch" href="https://cdn.jsdelivr.net"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.11.2/css/all.min.css"><link rel="stylesheet" href="/assets/css/style.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/afeld/bootstrap-toc@1.0.1/dist/bootstrap-toc.min.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/magnific-popup@1.1.0/dist/magnific-popup.min.css"> <script src="https://cdn.jsdelivr.net/npm/jquery@3/dist/jquery.min.js"></script><body data-spy="scroll" data-target="#toc"><div id="sidebar" class="d-flex flex-column align-items-end" lang="en"><div class="profile-wrapper text-center"><div id="avatar"> <a href="/" alt="avatar" class="mx-auto"> </a></div><div class="site-title mt-3"> <a href="/">Null Section</a></div><div class="site-subtitle font-italic">nothing here.</div></div><ul class="w-100"><li class="nav-item"> <a href="/" class="nav-link"> <i class="fa-fw fas fa-home ml-xl-3 mr-xl-3 unloaded"></i> <span>HOME</span> </a><li class="nav-item"> <a href="/categories/" class="nav-link"> <i class="fa-fw fas fa-stream ml-xl-3 mr-xl-3 unloaded"></i> <span>CATEGORIES</span> </a><li class="nav-item"> <a href="/tags/" class="nav-link"> <i class="fa-fw fas fa-tag ml-xl-3 mr-xl-3 unloaded"></i> <span>TAGS</span> </a><li class="nav-item"> <a href="/archives/" class="nav-link"> <i class="fa-fw fas fa-archive ml-xl-3 mr-xl-3 unloaded"></i> <span>ARCHIVES</span> </a><li class="nav-item"> <a href="/about/" class="nav-link"> <i class="fa-fw fas fa-info-circle ml-xl-3 mr-xl-3 unloaded"></i> <span>ABOUT</span> </a></ul><div class="sidebar-bottom mt-auto d-flex flex-wrap justify-content-center align-items-center"> <a href="https://github.com/psy0231" aria-label="github" target="_blank" rel="noopener"> <i class="fab fa-github"></i> </a> <a href="https://twitter.com/twitter_username" aria-label="twitter" target="_blank" rel="noopener"> <i class="fab fa-twitter"></i> </a> <a href=" javascript:location.href = 'mailto:' + ['psy0231','gmail.com'].join('@')" aria-label="email" > <i class="fas fa-envelope"></i> </a> <a href="/feed.xml" aria-label="rss" > <i class="fas fa-rss"></i> </a></div></div><div id="topbar-wrapper" class="row justify-content-center topbar-down"><div id="topbar" class="col-11 d-flex h-100 align-items-center justify-content-between"> <span id="breadcrumb"> <span> <a href="/"> Home </a> </span> <span>12. async/await_3 Excention 2</span> </span> <i id="sidebar-trigger" class="fas fa-bars fa-fw"></i><div id="topbar-title"> Post</div><i id="search-trigger" class="fas fa-search fa-fw"></i> <span id="search-wrapper" class="align-items-center"> <i class="fas fa-search fa-fw"></i> <input class="form-control" id="search-input" type="search" aria-label="search" autocomplete="off" placeholder="Search..."> <i class="fa fa-times-circle fa-fw" id="search-cleaner"></i> </span> <span id="search-cancel" >Cancel</span></div></div><div id="main-wrapper"><div id="main"><div class="row"><div id="core-wrapper" class="col-12 col-lg-11 col-xl-8"><div class="post pl-1 pr-1 pl-sm-2 pr-sm-2 pl-md-4 pr-md-4"><h1 data-toc-skip>12. async/await_3 Excention 2</h1><div class="post-meta text-muted"><div> By <em> <a href="https://twitter.com/username">SooyongPark</a> </em></div><div class="d-flex"><div> <span> Posted <em class="timeago" date="2021-03-31 12:00:00 +0900" data-toggle="tooltip" data-placement="bottom" title="Wed, Mar 31, 2021, 12:00 PM +0900" >Mar 31, 2021</em> </span> <span class="readtime" data-toggle="tooltip" data-placement="bottom" title="1306 words"> <em>7 min</em> read</span></div></div></div><div class="post-content"><h2 id="about-exception-of-void-return">about exception of void return.<a href="#about-exception-of-void-return" class="anchor"><i class="fas fa-hashtag"></i></a></h2></h2><ul><li>쉽게, sync에서 먼저.<div class="language-c# highlighter-rouge"><div class="code-header"> <span label-text="C#"><i class="fas fa-code small"></i></span> <button aria-label="copy" title-succeed="Copied!"><i class="far fa-clipboard"></i></button></div><div class="highlight"><code><table class="rouge-table"><tbody><tr><td class="rouge-gutter gl"><pre class="lineno">1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
</pre><td class="rouge-code"><pre><span class="k">class</span> <span class="nc">asaw_4_sync</span>
<span class="p">{</span>
    <span class="k">public</span> <span class="k">void</span> <span class="nf">ThrowException</span><span class="p">()</span>
    <span class="p">{</span>
        <span class="k">throw</span> <span class="k">new</span> <span class="nf">InvalidOperationException</span><span class="p">();</span>
    <span class="p">}</span>
    <span class="k">public</span> <span class="k">void</span> <span class="nf">SyncExceptions</span><span class="p">()</span>
    <span class="p">{</span>
        <span class="k">try</span>
        <span class="p">{</span>
            <span class="nf">ThrowException</span><span class="p">();</span>
        <span class="p">}</span>
        <span class="k">catch</span> <span class="p">(</span><span class="n">Exception</span><span class="p">)</span>
        <span class="p">{</span>
            <span class="c1">// The exception is never caught here!</span>
            <span class="k">throw</span><span class="p">;</span>
        <span class="p">}</span>
    <span class="p">}</span>
<span class="p">}</span>
<span class="c1">////////////////////////////////////////////////////</span>
<span class="k">private</span> <span class="k">void</span> <span class="nf">button1_Click</span><span class="p">(</span><span class="kt">object</span> <span class="n">sender</span><span class="p">,</span> <span class="n">EventArgs</span> <span class="n">e</span><span class="p">)</span>
<span class="p">{</span>
    <span class="k">try</span>
    <span class="p">{</span>
        <span class="n">aa4s</span><span class="p">.</span><span class="nf">SyncExceptions</span><span class="p">();</span>
    <span class="p">}</span>
    <span class="k">catch</span> <span class="p">(</span><span class="n">Exception</span> <span class="n">ex</span><span class="p">)</span>
    <span class="p">{</span>
        <span class="n">textBox1</span><span class="p">.</span><span class="nf">AppendText</span><span class="p">(</span><span class="n">ex</span><span class="p">.</span><span class="n">Message</span> <span class="p">+</span> <span class="n">Environment</span><span class="p">.</span><span class="n">NewLine</span><span class="p">);</span>
    <span class="p">}</span>
<span class="p">}</span>
</pre></table></code></div></div><ul><li>예상 가능한 결과로<br /> 호출은 button event =&gt; SyncExceptions() =&gt; ThrowException() 으로, <br /> Exceptions은 ThrowException() =&gt; SyncExceptions() =&gt; button event로<br /> 잘 타고 온다. 항상 보던 당연한 결말.</ul><li>위 방식을 async로 바꿔해본다.<div class="language-c# highlighter-rouge"><div class="code-header"> <span label-text="C#"><i class="fas fa-code small"></i></span> <button aria-label="copy" title-succeed="Copied!"><i class="far fa-clipboard"></i></button></div><div class="highlight"><code><table class="rouge-table"><tbody><tr><td class="rouge-gutter gl"><pre class="lineno">1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
</pre><td class="rouge-code"><pre><span class="k">class</span> <span class="nc">ASAW_4_async_1</span>
<span class="p">{</span>
    <span class="k">public</span> <span class="k">async</span> <span class="k">void</span> <span class="nf">ThrowException</span><span class="p">()</span>
    <span class="p">{</span>
        <span class="k">throw</span> <span class="k">new</span> <span class="nf">InvalidOperationException</span><span class="p">();</span>
    <span class="p">}</span>
    <span class="k">public</span> <span class="k">void</span> <span class="nf">AsyncExceptions</span><span class="p">()</span>
    <span class="p">{</span>
        <span class="k">try</span>
        <span class="p">{</span>
            <span class="nf">ThrowException</span><span class="p">();</span>
        <span class="p">}</span>
        <span class="k">catch</span> <span class="p">(</span><span class="n">Exception</span><span class="p">)</span>
        <span class="p">{</span>
            <span class="c1">// The exception is never caught here!</span>
            <span class="k">throw</span><span class="p">;</span>
        <span class="p">}</span>
    <span class="p">}</span>
<span class="p">}</span>
<span class="c1">//////////////////</span>
<span class="k">private</span> <span class="k">void</span> <span class="nf">button2_Click</span><span class="p">(</span><span class="kt">object</span> <span class="n">sender</span><span class="p">,</span> <span class="n">EventArgs</span> <span class="n">e</span><span class="p">)</span>
<span class="p">{</span>
    <span class="k">try</span>
    <span class="p">{</span>
        <span class="n">aa4a_1</span><span class="p">.</span><span class="nf">AsyncExceptions</span><span class="p">();</span>
    <span class="p">}</span>
    <span class="k">catch</span> <span class="p">(</span><span class="n">Exception</span> <span class="n">ex</span><span class="p">)</span>
    <span class="p">{</span>
        <span class="n">textBox1</span><span class="p">.</span><span class="nf">AppendText</span><span class="p">(</span><span class="n">ex</span><span class="p">.</span><span class="n">Message</span> <span class="p">+</span> <span class="n">Environment</span><span class="p">.</span><span class="n">NewLine</span><span class="p">);</span>
    <span class="p">}</span>
<span class="p">}</span>
</pre></table></code></div></div><ul><li>바뀐점은 ThrowException()가 async로 된것, 또 하지말라던 void로 한것.<li>호출은 button event =&gt; AsyncExceptions() =&gt; ThrowException()으로 동일,<br /> Exception은 throw new InvalidOperationException(); 에서 멈춘다.<br /> 저 라인에서 throw를 못한다.</ul><li>그럼 void가 아니라면??<div class="language-c# highlighter-rouge"><div class="code-header"> <span label-text="C#"><i class="fas fa-code small"></i></span> <button aria-label="copy" title-succeed="Copied!"><i class="far fa-clipboard"></i></button></div><div class="highlight"><code><table class="rouge-table"><tbody><tr><td class="rouge-gutter gl"><pre class="lineno">1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
</pre><td class="rouge-code"><pre><span class="k">class</span> <span class="nc">ASAW_4_async_2</span>
<span class="p">{</span>
    <span class="k">public</span> <span class="k">async</span> <span class="n">Task</span> <span class="nf">ThrowException</span><span class="p">()</span>
    <span class="p">{</span>
        <span class="k">throw</span> <span class="k">new</span> <span class="nf">InvalidOperationException</span><span class="p">();</span>
    <span class="p">}</span>
    <span class="k">public</span> <span class="k">void</span> <span class="nf">AsyncExceptions</span><span class="p">()</span>
    <span class="p">{</span>
        <span class="k">try</span>
        <span class="p">{</span>
            <span class="nf">ThrowException</span><span class="p">();</span>
        <span class="p">}</span>
        <span class="k">catch</span> <span class="p">(</span><span class="n">Exception</span><span class="p">)</span>
        <span class="p">{</span>
            <span class="c1">// The exception is never caught here!</span>
            <span class="k">throw</span><span class="p">;</span>
        <span class="p">}</span>
    <span class="p">}</span>
<span class="p">}</span>
<span class="c1">////////////////////////////////////////////////////////</span>
<span class="k">private</span> <span class="k">void</span> <span class="nf">button2_Click</span><span class="p">(</span><span class="kt">object</span> <span class="n">sender</span><span class="p">,</span> <span class="n">EventArgs</span> <span class="n">e</span><span class="p">)</span>
<span class="p">{</span>
    <span class="k">try</span>
    <span class="p">{</span>
        <span class="n">aa4a_1</span><span class="p">.</span><span class="nf">AsyncExceptions</span><span class="p">();</span>
    <span class="p">}</span>
    <span class="k">catch</span> <span class="p">(</span><span class="n">Exception</span> <span class="n">ex</span><span class="p">)</span>
    <span class="p">{</span>
        <span class="n">textBox1</span><span class="p">.</span><span class="nf">AppendText</span><span class="p">(</span><span class="n">ex</span><span class="p">.</span><span class="n">Message</span> <span class="p">+</span> <span class="n">Environment</span><span class="p">.</span><span class="n">NewLine</span><span class="p">);</span>
    <span class="p">}</span>
<span class="p">}</span>
</pre></table></code></div></div><ul><li>위 ASAW_4_async_1과의 차이점은 void에서 Task가 된것.<li>호출 순서야 같은데 이번엔 throw new InvalidOperationException();에서<br /> Exception도 안잡히고 끝난다. 아무런 반응이 없다.<li>이 전 async/await_3 excention 1에서 말하는 The exception is never caught here!<br /> 은 Exception이 잡히건 말건 해당 try/catch는 절대 안들어온다는 뜻인것같다.</ul><li>그럼 되는방법은?<div class="language-c# highlighter-rouge"><div class="code-header"> <span label-text="C#"><i class="fas fa-code small"></i></span> <button aria-label="copy" title-succeed="Copied!"><i class="far fa-clipboard"></i></button></div><div class="highlight"><code><table class="rouge-table"><tbody><tr><td class="rouge-gutter gl"><pre class="lineno">1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
</pre><td class="rouge-code"><pre><span class="k">class</span> <span class="nc">ASAW_4_async_3</span>
<span class="p">{</span>
    <span class="c1">//public async void ThrowException()</span>
    <span class="c1">//{</span>
    <span class="c1">//    throw new InvalidOperationException();</span>
    <span class="c1">//}</span>
    <span class="k">public</span> <span class="k">async</span> <span class="n">Task</span> <span class="nf">ThrowException</span><span class="p">()</span>
    <span class="p">{</span>
        <span class="k">throw</span> <span class="k">new</span> <span class="nf">InvalidOperationException</span><span class="p">();</span>
    <span class="p">}</span>
    <span class="k">public</span> <span class="k">async</span> <span class="k">void</span> <span class="nf">AsyncExceptions</span><span class="p">()</span>
    <span class="p">{</span>
        <span class="k">try</span>
        <span class="p">{</span>
            <span class="k">await</span> <span class="nf">ThrowException</span><span class="p">();</span>
        <span class="p">}</span>
        <span class="k">catch</span> <span class="p">(</span><span class="n">Exception</span><span class="p">)</span>
        <span class="p">{</span>
            <span class="c1">// The exception is never caught here!</span>
            <span class="k">throw</span><span class="p">;</span>
        <span class="p">}</span>
    <span class="p">}</span>
<span class="p">}</span>
<span class="c1">///////////////////////////////////////////////////////////</span>
<span class="k">private</span> <span class="k">void</span> <span class="nf">button4_Click</span><span class="p">(</span><span class="kt">object</span> <span class="n">sender</span><span class="p">,</span> <span class="n">EventArgs</span> <span class="n">e</span><span class="p">)</span>
<span class="p">{</span>
    <span class="k">try</span>
    <span class="p">{</span>
        <span class="n">aa4a_3</span><span class="p">.</span><span class="nf">AsyncExceptions</span><span class="p">();</span>
    <span class="p">}</span>
    <span class="k">catch</span> <span class="p">(</span><span class="n">Exception</span> <span class="n">ex</span><span class="p">)</span>
    <span class="p">{</span>
        <span class="n">textBox1</span><span class="p">.</span><span class="nf">AppendText</span><span class="p">(</span><span class="n">ex</span><span class="p">.</span><span class="n">Message</span> <span class="p">+</span> <span class="n">Environment</span><span class="p">.</span><span class="n">NewLine</span><span class="p">);</span>
    <span class="p">}</span>
<span class="p">}</span>
</pre></table></code></div></div><ul><li>다른점<ul><li>AsyncExceptions : async에 있어야할 await가 붙음<li>async void를 그대로 하면 호출할때 에러남 async Task로 수정.</ul><li>결과는 AsyncExceptions() 의 catch 부분에서 잡힌다.<li>따라서 정상적인 처리는 되는것처럼 보이는데<br /> AsyncExceptions에서 button event로 throw는 안됨.<li><p>이 부분은 다시 button4_Click를 async void로 수정하고<br /> aa4a_3.AsyncExceptions(); 호출을 await로 한다.<br /> AsyncExceptions()도 async void에서 async Task로 수정.</p><div class="language-c# highlighter-rouge"><div class="code-header"> <span label-text="C#"><i class="fas fa-code small"></i></span> <button aria-label="copy" title-succeed="Copied!"><i class="far fa-clipboard"></i></button></div><div class="highlight"><code><table class="rouge-table"><tbody><tr><td class="rouge-gutter gl"><pre class="lineno">1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
</pre><td class="rouge-code"><pre><span class="k">class</span> <span class="nc">ASAW_4_async_3</span>
<span class="p">{</span>
    <span class="c1">//public async void ThrowException()</span>
    <span class="c1">//{</span>
    <span class="c1">//    throw new InvalidOperationException();</span>
    <span class="c1">//}</span>
    <span class="k">public</span> <span class="k">async</span> <span class="n">Task</span> <span class="nf">ThrowException</span><span class="p">()</span>
    <span class="p">{</span>
        <span class="k">throw</span> <span class="k">new</span> <span class="nf">InvalidOperationException</span><span class="p">();</span>
    <span class="p">}</span>
    <span class="k">public</span> <span class="k">async</span> <span class="n">Task</span> <span class="nf">AsyncExceptions</span><span class="p">()</span>
    <span class="p">{</span>
        <span class="k">try</span>
        <span class="p">{</span>
            <span class="k">await</span> <span class="nf">ThrowException</span><span class="p">();</span>
        <span class="p">}</span>
        <span class="k">catch</span> <span class="p">(</span><span class="n">Exception</span><span class="p">)</span>
        <span class="p">{</span>
            <span class="c1">// The exception is never caught here!</span>
            <span class="k">throw</span><span class="p">;</span>
        <span class="p">}</span>
    <span class="p">}</span>
<span class="p">}</span>
<span class="c1">///////////////////////////////////////////////////////////</span>
<span class="k">private</span> <span class="k">async</span> <span class="k">void</span> <span class="nf">button4_Click</span><span class="p">(</span><span class="kt">object</span> <span class="n">sender</span><span class="p">,</span> <span class="n">EventArgs</span> <span class="n">e</span><span class="p">)</span>
<span class="p">{</span>
    <span class="k">try</span>
    <span class="p">{</span>
        <span class="k">await</span> <span class="n">aa4a_3</span><span class="p">.</span><span class="nf">AsyncExceptions</span><span class="p">();</span>
    <span class="p">}</span>
    <span class="k">catch</span> <span class="p">(</span><span class="n">Exception</span> <span class="n">ex</span><span class="p">)</span>
    <span class="p">{</span>
        <span class="n">textBox1</span><span class="p">.</span><span class="nf">AppendText</span><span class="p">(</span><span class="n">ex</span><span class="p">.</span><span class="n">Message</span> <span class="p">+</span> <span class="n">Environment</span><span class="p">.</span><span class="n">NewLine</span><span class="p">);</span>
    <span class="p">}</span>
<span class="p">}</span>
</pre></table></code></div></div><ul><li>이렇게 되면 button event에서 정상적으로 잡아냄 원래 sync처럼.<li>void AsyncExceptions()에서 Task AsyncExceptions()으로<br /> 수정했는데 되는거 보면 Task에 뭔가 있겠지?<h2 id="so">so…<a href="#so" class="anchor"><i class="fas fa-hashtag"></i></a></h2></h2></ul></ul><li>결과를 보면 async 함수들은 Task를 이용해 그 안에 정보를 넘기는듯하다.<br /> 근데 return이 Task니까 당연한건가 싶은데<br /> data적인return 외에도 method적인 측면에서 실행 결과까지.<br /> 그래서 void return의 경우.. 넘길 수 없어서 그 선에서 끝내는건가??<li><p>무튼 return되는 Task에는 Exception까지 있는것같은데 다시,<br /> async/await_3 excention 2 의 Avoid Async Void 를 보면</p><blockquote><p>Async void 메서드는 오류 처리 의미가 다르다.<br /> 비동기 작업 또는 비동기 Task&lt;T&gt; 메서드에서 예외가 throw되면<br /> 해당 예외가 캡처되어 Task 개체에 배치함.<br /> async void 메서드를 사용하면 Task 개체가 없으므로<br /> async void 메서드에서 throw 된 모든 예외는<br /> async void 메서드가 시작될 때 활성화 된 SynchronizationContext에서 직접 발생.<br /> 다음은 비동기 void 메서드에서 throw 된 exception을 catch못한 경우.</p></blockquote><p>이 말이 이제 이해가 감.</p><li>그럼 event를 제외하고 async void를 쓰지 말라했는데<br /> exception의 최종 목적지이면 상관이 없어보임.<br /> 근데 이렇게 따지느니 Task로 도배하는게 맞는것같기도하고..<li>사실 async/await가 해주는 일이 더 많고<br /> 이것저것 더 볼게 많은것같은데 이거 찾으면서, 또는 이 관련해 더 많은건 아래.</ul><h2 id="참고">참고<a href="#참고" class="anchor"><i class="fas fa-hashtag"></i></a></h2></h2><ul><li><a href="https://www.youtube.com/watch?v=HkLhKyoh3sI">Async 쓸까말까 및 주의할 점</a><li><a href="https://www.youtube.com/watch?v=-tzfIeZGL5o">async void가 안좋은 이유</a><li><a href="https://www.sysnet.pe.kr/2/0/11414">async 메서드의 void 반환 타입 사용에 대하여</a><li><a href="https://www.sysnet.pe.kr/2/0/11351">C# 컴파일러 대신 직접 구현하는 비동기(async/await) 코드</a><li><a href="https://m.blog.naver.com/PostView.nhn?blogId=vactorman&amp;logNo=221180404572&amp;proxyReferer=https:%2F%2Fwww.google.com%2F">async void 메서드의 예외는 정말 Fire &amp; forget 일까?</a></ul></div><div class="post-tail-wrapper text-muted"><div class="post-meta mb-3"> <i class="far fa-folder-open fa-fw mr-1"></i> <a href='/categories/grind/'>Grind</a>, <a href='/categories/c/'>C#</a></div><div class="post-tags"> <i class="fa fa-tags fa-fw mr-1"></i> <a href="/tags/c/" class="post-tag no-text-decoration" >c#</a> <a href="/tags/asynchronous/" class="post-tag no-text-decoration" >asynchronous</a></div><div class="post-tail-bottom d-flex justify-content-between align-items-center mt-3 pt-5 pb-2"><div class="license-wrapper"> This post is licensed under <a href="https://creativecommons.org/licenses/by/4.0/"> CC BY 4.0 </a> by the author.</div><div class="share-wrapper"> <span class="share-label text-muted mr-1">Share</span> <span class="share-icons"> <a href="https://twitter.com/intent/tweet?text=12. async/await_3 Excention 2 - Null Section&url=https://psy0231.github.io/posts/CS_12_Async&Await_4/" data-toggle="tooltip" data-placement="top" title="Twitter" target="_blank" rel="noopener" aria-label="Twitter"> <i class="fa-fw fab fa-twitter"></i> </a> <a href="https://www.facebook.com/sharer/sharer.php?title=12. async/await_3 Excention 2 - Null Section&u=https://psy0231.github.io/posts/CS_12_Async&Await_4/" data-toggle="tooltip" data-placement="top" title="Facebook" target="_blank" rel="noopener" aria-label="Facebook"> <i class="fa-fw fab fa-facebook-square"></i> </a> <a href="https://telegram.me/share?text=12. async/await_3 Excention 2 - Null Section&url=https://psy0231.github.io/posts/CS_12_Async&Await_4/" data-toggle="tooltip" data-placement="top" title="Telegram" target="_blank" rel="noopener" aria-label="Telegram"> <i class="fa-fw fab fa-telegram"></i> </a> <i id="copy-link" class="fa-fw fas fa-link small" data-toggle="tooltip" data-placement="top" title="Copy link" title-succeed="Link copied successfully!"> </i> </span></div></div></div></div></div><div id="panel-wrapper" class="col-xl-3 pl-2 text-muted topbar-down"><div class="access"><div id="access-lastmod" class="post"><div class="panel-heading">Recent Update</div><ul class="post-content pl-0 pb-1 ml-1 mt-2"><li><a href="/posts/Python_dict/">dict</a><li><a href="/posts/Python_Var_Type/">Variable & Data Type</a><li><a href="/posts/Docker_4_Container_Option/">Docker 4 - Container Option</a><li><a href="/posts/Docker_3_Container/">Docker 3 - Container</a><li><a href="/posts/Docker_2_Image/">Docker 2 - Image</a></ul></div><div id="access-tags"><div class="panel-heading">Trending Tags</div><div class="d-flex flex-wrap mt-3 mb-1 mr-3"> <a class="post-tag" href="/tags/c/">c#</a> <a class="post-tag" href="/tags/python/">python</a> <a class="post-tag" href="/tags/docker/">docker</a> <a class="post-tag" href="/tags/git/">git</a> <a class="post-tag" href="/tags/asynchronous/">asynchronous</a> <a class="post-tag" href="/tags/data-type/">data type</a> <a class="post-tag" href="/tags/container/">container</a> <a class="post-tag" href="/tags/getting-started/">getting started</a> <a class="post-tag" href="/tags/io/">io</a> <a class="post-tag" href="/tags/logger/">logger</a></div></div></div><script src="https://cdn.jsdelivr.net/gh/afeld/bootstrap-toc@1.0.1/dist/bootstrap-toc.min.js"></script><div id="toc-wrapper" class="pl-0 pr-4 mb-5"><div class="panel-heading pl-3 pt-2 mb-2">Contents</div><nav id="toc" data-toggle="toc"></nav></div></div></div><div class="row"><div class="col-12 col-lg-11 col-xl-8"><div id="tail-wrapper" class="pl-1 pr-1 pl-sm-2 pr-sm-2 pl-md-4 pr-md-4"><div id="related-posts" class="mt-5 mb-2 mb-sm-4"><h3 class="pt-2 mt-1 mb-4 ml-1" data-toc-skip>Further Reading</h3><div class="card-deck mb-4"><div class="card"> <a href="/posts/CS_5_Async&Await_1/"><div class="card-body"> <em class="timeago small" date="2020-03-13 15:00:00 +0900" >Mar 13, 2020</em><h3 class="pt-0 mt-1 mb-3" data-toc-skip>5. async/await_1 (sync/async, block/non-block)</h3><div class="text-muted small"><p> Build Up Action/Func - Task - async/await 왜? async라는 키워드를 자주 접하는것같은데 막상 써본적은 적거나 저게 어떤식으로 동작하는지 몰라서 시작함 시작은 async/await를 바로 쓸라다가 그 와중에 자주보이는 관련 키워드부터 해야지 싶어 build up부터하다 이 지경이 됨 sync/as...</p></div></div></a></div><div class="card"> <a href="/posts/CS_10_Async&Await_2/"><div class="card-body"> <em class="timeago small" date="2020-12-24 18:00:00 +0900" >Dec 24, 2020</em><h3 class="pt-0 mt-1 mb-3" data-toc-skip>10. async/await_2</h3><div class="text-muted small"><p> Asynchronous intro 다시 asynchronous programming를 async, await와 섞어서함. 따라서 본 내용은 이 전 async &amp;amp; await 1 의 내용과 위의 async, await 와 중복되는 내용이 많은데, 이부분은 아래 링크에도 있듯이 서로 연결되어있거나 순환적임. 무튼, 계속 비슷한 내용들을...</p></div></div></a></div><div class="card"> <a href="/posts/CS_11_Async&Await_3/"><div class="card-body"> <em class="timeago small" date="2021-03-30 18:00:00 +0900" >Mar 30, 2021</em><h3 class="pt-0 mt-1 mb-3" data-toc-skip>11. async/await_3 Excention 1</h3><div class="text-muted small"><p> AS/AW Example 필요해서 직접 만들었던 예시와 공부하면서 봤던 내용들이 충돌해서 .. source text파일을 읽고 table 형태로 만들고 grid에 넣음. 실제 오래 걸리던 데이터에서 1분정도만 잡아먹게 줄이고 해봄. 하던 과정 그대로 일단. example 1 // 실제 파일을 읽고 취합 후 구조화한 후, //...</p></div></div></a></div></div></div><div class="post-navigation d-flex justify-content-between"> <a href="/posts/CS_11_Async&Await_3/" class="btn btn-outline-primary" prompt="Older"><p>11. async/await_3 Excention 1</p></a> <a href="/posts/CS_13_Linq_1/" class="btn btn-outline-primary" prompt="Newer"><p>13. LINQ 1</p></a></div><div id="disqus_thread" class="pt-2 pb-2"><p class="text-center text-muted small"> Comments powered by <a href="https://disqus.com/">Disqus</a>.</p></div><script type="text/javascript"> var disqus_config = function () { this.page.url = 'https://psy0231.github.io/posts/CS_12_Async&Await_4/'; this.page.identifier = '/posts/CS_12_Async&Await_4/'; }; /* Lazy loading */ var disqus_observer = new IntersectionObserver(function (entries) { if(entries[0].isIntersecting) { (function () { var d = document, s = d.createElement('script'); s.src = 'https://https-psy0231-github-io.disqus.com/embed.js'; s.setAttribute('data-timestamp', +new Date()); (d.head || d.body).appendChild(s); })(); disqus_observer.disconnect(); } }, { threshold: [0] }); disqus_observer.observe(document.querySelector('#disqus_thread')); /* Auto switch theme */ function reloadDisqus() { /* Disqus hasn't been loaded */ if (typeof DISQUS === "undefined") { return; } if (document.readyState == 'complete') { DISQUS.reset({ reload: true, config: disqus_config }); } } const modeToggle = document.querySelector(".mode-toggle"); if (typeof modeToggle !== "undefined") { /* modeToggle.addEventListener('click', reloadDisqus); // not pretty for 'color-scheme' */ window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change', reloadDisqus); } </script></div></div></div><footer class="d-flex w-100 justify-content-center"><div class="d-flex justify-content-between align-items-center text-muted"><div class="footer-left"><p class="mb-0"> © 2023 <a href="https://twitter.com/username">SooyongPark</a>. <span data-toggle="tooltip" data-placement="top" title="Except where otherwise noted, the blog posts on this site are licensed under the Creative Commons Attribution 4.0 International (CC BY 4.0) License by the author.">Some rights reserved.</span></p></div><div class="footer-right"><p class="mb-0"> Powered by <a href="https://jekyllrb.com" target="_blank" rel="noopener">Jekyll</a> with <a href="https://github.com/cotes2020/jekyll-theme-chirpy" target="_blank" rel="noopener">Chirpy</a> theme.</p></div></div></footer></div><div id="search-result-wrapper" class="d-flex justify-content-center unloaded"><div class="col-12 col-sm-11 post-content"><div id="search-hints"><div id="access-tags"><div class="panel-heading">Trending Tags</div><div class="d-flex flex-wrap mt-3 mb-1 mr-3"> <a class="post-tag" href="/tags/c/">c#</a> <a class="post-tag" href="/tags/python/">python</a> <a class="post-tag" href="/tags/docker/">docker</a> <a class="post-tag" href="/tags/git/">git</a> <a class="post-tag" href="/tags/asynchronous/">asynchronous</a> <a class="post-tag" href="/tags/data-type/">data type</a> <a class="post-tag" href="/tags/container/">container</a> <a class="post-tag" href="/tags/getting-started/">getting started</a> <a class="post-tag" href="/tags/io/">io</a> <a class="post-tag" href="/tags/logger/">logger</a></div></div></div><div id="search-results" class="d-flex flex-wrap justify-content-center text-muted mt-3"></div></div></div></div><div id="mask"></div><a id="back-to-top" href="#" aria-label="back-to-top" class="btn btn-lg btn-box-shadow" role="button"> <i class="fas fa-angle-up"></i> </a> <script src="https://cdn.jsdelivr.net/npm/simple-jekyll-search@1.10.0/dest/simple-jekyll-search.min.js"></script> <script> SimpleJekyllSearch({ searchInput: document.getElementById('search-input'), resultsContainer: document.getElementById('search-results'), json: '/assets/js/data/search.json', searchResultTemplate: '<div class="pl-1 pr-1 pl-sm-2 pr-sm-2 pl-lg-4 pr-lg-4 pl-xl-0 pr-xl-0"> <a href="{url}">{title}</a><div class="post-meta d-flex flex-column flex-sm-row text-muted mt-1 mb-1"> {categories} {tags}</div><p>{snippet}</p></div>', noResultsText: '<p class="mt-5">Oops! No result founds.</p>', templateMiddleware: function(prop, value, template) { if (prop === 'categories') { if (value === '') { return `${value}`; } else { return `<div class="mr-sm-4"><i class="far fa-folder fa-fw"></i>${value}</div>`; } } if (prop === 'tags') { if (value === '') { return `${value}`; } else { return `<div><i class="fa fa-tag fa-fw"></i>${value}</div>`; } } } }); </script> <script src="https://cdn.jsdelivr.net/combine/npm/lozad/dist/lozad.min.js,npm/magnific-popup@1/dist/jquery.magnific-popup.min.js,npm/clipboard@2/dist/clipboard.min.js"></script> <script defer src="/assets/js/dist/post.min.js"></script> <script src="https://cdn.jsdelivr.net/combine/npm/popper.js@1.16.1,npm/bootstrap@4/dist/js/bootstrap.min.js"></script> <script defer src="/app.js"></script> <script defer src="https://www.googletagmanager.com/gtag/js?id=UA-160640437-1"></script> <script> document.addEventListener("DOMContentLoaded", function(event) { window.dataLayer = window.dataLayer || []; function gtag(){dataLayer.push(arguments);} gtag('js', new Date()); gtag('config', 'UA-160640437-1'); }); </script>
